package com.chefpro.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import com.chefpro.model.AppLanguage
import com.chefpro.model.DishMenuStatus
import com.chefpro.model.DishType

data class AppStrings(
    val appTitle: String,
    val login: String,
    val logout: String,
    val enterPin: String,
    val wrongPin: String,
    val selectEmployee: String,
    val dashboard: String,
    val techCards: String,
    val inventory: String,
    val search: String,
    val settings: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val add: String,
    val back: String,
    val next: String,
    val skip: String,
    val getStarted: String,
    val restaurantName: String,
    val greetingMorning: String,
    val greetingDay: String,
    val greetingEvening: String,
    val greetingNight: String,
    val dishes: String,
    val stockValue: String,
    val lowStock: String,
    val foodCost: String,
    val foodCostWarning: String,
    val expiringSoon: String,
    val expired: String,
    val quickActions: String,
    val addDish: String,
    val addProduct: String,
    val scanBarcode: String,
    val noDishes: String,
    val noInventory: String,
    val noResults: String,
    val searchHint: String,
    val category: String,
    val name: String,
    val price: String,
    val quantity: String,
    val unit: String,
    val minQuantity: String,
    val pricePerUnit: String,
    val barcode: String,
    val expiryDate: String,
    val ingredients: String,
    val steps: String,
    val allergens: String,
    val nutrition: String,
    val calories: String,
    val proteins: String,
    val fats: String,
    val carbs: String,
    val cookTime: String,
    val portionWeight: String,
    val salePrice: String,
    val cost: String,
    val margin: String,
    val recipeVersions: String,
    val saveVersion: String,
    val favorite: String,
    val menuStatus: String,
    val dishType: String,
    val instruction: String,
    val addIngredient: String,
    val addStep: String,
    val productName: String,
    val yieldFactor: String,
    val stepTip: String,
    val durationMinutes: String,
    val permissionDenied: String,
    val offline: String,
    val syncing: String,
    val pendingSync: String,
    val onboardingWelcome: String,
    val onboardingWelcomeBody: String,
    val onboardingTechCards: String,
    val onboardingTechCardsBody: String,
    val onboardingInventory: String,
    val onboardingInventoryBody: String,
    val onboardingSetup: String,
    val onboardingSetupBody: String,
    val dishesCount: String,
    val productsCount: String,
    val viewAll: String,
    val unmatchedIngredients: String,
    val stopList: String,
    val goList: String,
    val dishTypeLabels: Map<DishType, String>,
    val menuStatusLabels: Map<DishMenuStatus, String>,
)

val LocalAppStrings = staticCompositionLocalOf { appStrings(AppLanguage.RUSSIAN) }

@Composable
fun rememberAppStrings(language: AppLanguage): AppStrings = appStrings(language)

fun appStrings(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.RUSSIAN -> AppStrings(
        appTitle = "ChefPro",
        login = "Войти",
        logout = "Выйти",
        enterPin = "Введите PIN",
        wrongPin = "Неверный PIN",
        selectEmployee = "Выберите сотрудника",
        dashboard = "Главная",
        techCards = "Техкарты",
        inventory = "Склад",
        search = "Поиск",
        settings = "Настройки",
        save = "Сохранить",
        cancel = "Отмена",
        delete = "Удалить",
        edit = "Изменить",
        add = "Добавить",
        back = "Назад",
        next = "Далее",
        skip = "Пропустить",
        getStarted = "Начать работу",
        restaurantName = "Название ресторана",
        greetingMorning = "Доброе утро",
        greetingDay = "Добрый день",
        greetingEvening = "Добрый вечер",
        greetingNight = "Доброй ночи",
        dishes = "Блюда",
        stockValue = "Склад",
        lowStock = "Мало на складе",
        foodCost = "Food cost",
        foodCostWarning = "Высокий food cost",
        expiringSoon = "Срок истекает",
        expired = "Просрочено",
        quickActions = "Быстрые действия",
        addDish = "Новое блюдо",
        addProduct = "Новый продукт",
        scanBarcode = "Сканировать штрихкод",
        noDishes = "Нет техкарт",
        noInventory = "Склад пуст",
        noResults = "Ничего не найдено",
        searchHint = "Поиск блюд и продуктов…",
        category = "Категория",
        name = "Название",
        price = "Цена",
        quantity = "Количество",
        unit = "Ед. изм.",
        minQuantity = "Мин. остаток",
        pricePerUnit = "Цена за ед.",
        barcode = "Штрихкод",
        expiryDate = "Срок годности",
        ingredients = "Ингредиенты",
        steps = "Шаги приготовления",
        allergens = "Аллергены",
        nutrition = "КБЖУ",
        calories = "Калории",
        proteins = "Белки",
        fats = "Жиры",
        carbs = "Углеводы",
        cookTime = "Время готовки, мин",
        portionWeight = "Вес порции",
        salePrice = "Цена продажи",
        cost = "Себестоимость",
        margin = "Маржа",
        recipeVersions = "Версии рецепта",
        saveVersion = "Сохранить версию",
        favorite = "Избранное",
        menuStatus = "Статус в меню",
        dishType = "Тип",
        instruction = "Инструкция",
        addIngredient = "Добавить ингредиент",
        addStep = "Добавить шаг",
        productName = "Продукт",
        yieldFactor = "Выход",
        stepTip = "Совет",
        durationMinutes = "Минут",
        permissionDenied = "Нет доступа",
        offline = "Нет сети",
        syncing = "Синхронизация…",
        pendingSync = "Ожидает синхронизации",
        onboardingWelcome = "Добро пожаловать в ChefPro",
        onboardingWelcomeBody = "Профессиональный инструмент для управления кухней, складом и food cost вашего ресторана.",
        onboardingTechCards = "Техкарты и рецепты",
        onboardingTechCardsBody = "Ведите техкарты с ингредиентами, шагами, аллергенами и автоматическим расчётом себестоимости.",
        onboardingInventory = "Склад и остатки",
        onboardingInventoryBody = "Контролируйте остатки, сроки годности и получайте уведомления о низких запасах.",
        onboardingSetup = "Настройка",
        onboardingSetupBody = "Укажите название ресторана — можно изменить позже в настройках.",
        dishesCount = "блюд",
        productsCount = "продуктов",
        viewAll = "Все",
        unmatchedIngredients = "Не найдены на складе",
        stopList = "Стоп-лист",
        goList = "Go-лист",
        dishTypeLabels = mapOf(
            DishType.DISH to "Блюдо",
            DishType.SEMIFINISHED to "Полуфабрикат",
        ),
        menuStatusLabels = mapOf(
            DishMenuStatus.ACTIVE to "Активное",
            DishMenuStatus.SEASONAL to "Сезонное",
            DishMenuStatus.REMOVED to "Снято",
        ),
    )
    AppLanguage.ENGLISH -> AppStrings(
        appTitle = "ChefPro",
        login = "Sign in",
        logout = "Sign out",
        enterPin = "Enter PIN",
        wrongPin = "Wrong PIN",
        selectEmployee = "Select employee",
        dashboard = "Dashboard",
        techCards = "Recipes",
        inventory = "Inventory",
        search = "Search",
        settings = "Settings",
        save = "Save",
        cancel = "Cancel",
        delete = "Delete",
        edit = "Edit",
        add = "Add",
        back = "Back",
        next = "Next",
        skip = "Skip",
        getStarted = "Get started",
        restaurantName = "Restaurant name",
        greetingMorning = "Good morning",
        greetingDay = "Good afternoon",
        greetingEvening = "Good evening",
        greetingNight = "Good night",
        dishes = "Dishes",
        stockValue = "Stock",
        lowStock = "Low stock",
        foodCost = "Food cost",
        foodCostWarning = "High food cost",
        expiringSoon = "Expiring soon",
        expired = "Expired",
        quickActions = "Quick actions",
        addDish = "New dish",
        addProduct = "New product",
        scanBarcode = "Scan barcode",
        noDishes = "No recipes yet",
        noInventory = "Inventory is empty",
        noResults = "No results",
        searchHint = "Search dishes and products…",
        category = "Category",
        name = "Name",
        price = "Price",
        quantity = "Quantity",
        unit = "Unit",
        minQuantity = "Min stock",
        pricePerUnit = "Price per unit",
        barcode = "Barcode",
        expiryDate = "Expiry date",
        ingredients = "Ingredients",
        steps = "Cooking steps",
        allergens = "Allergens",
        nutrition = "Nutrition",
        calories = "Calories",
        proteins = "Protein",
        fats = "Fat",
        carbs = "Carbs",
        cookTime = "Cook time, min",
        portionWeight = "Portion weight",
        salePrice = "Sale price",
        cost = "Cost",
        margin = "Margin",
        recipeVersions = "Recipe versions",
        saveVersion = "Save version",
        favorite = "Favorite",
        menuStatus = "Menu status",
        dishType = "Type",
        instruction = "Instruction",
        addIngredient = "Add ingredient",
        addStep = "Add step",
        productName = "Product",
        yieldFactor = "Yield",
        stepTip = "Tip",
        durationMinutes = "Minutes",
        permissionDenied = "Access denied",
        offline = "Offline",
        syncing = "Syncing…",
        pendingSync = "Pending sync",
        onboardingWelcome = "Welcome to ChefPro",
        onboardingWelcomeBody = "Professional kitchen, inventory and food cost management for your restaurant.",
        onboardingTechCards = "Recipes & tech cards",
        onboardingTechCardsBody = "Manage recipes with ingredients, steps, allergens and automatic cost calculation.",
        onboardingInventory = "Inventory & stock",
        onboardingInventoryBody = "Track stock levels, expiry dates and get low stock alerts.",
        onboardingSetup = "Setup",
        onboardingSetupBody = "Enter your restaurant name — you can change it later in settings.",
        dishesCount = "dishes",
        productsCount = "products",
        viewAll = "View all",
        unmatchedIngredients = "Not found in inventory",
        stopList = "Stop list",
        goList = "Go list",
        dishTypeLabels = mapOf(
            DishType.DISH to "Dish",
            DishType.SEMIFINISHED to "Semifinished",
        ),
        menuStatusLabels = mapOf(
            DishMenuStatus.ACTIVE to "Active",
            DishMenuStatus.SEASONAL to "Seasonal",
            DishMenuStatus.REMOVED to "Removed",
        ),
    )
}

fun DishType.localized(language: AppLanguage): String =
    appStrings(language).dishTypeLabels[this] ?: name

fun DishMenuStatus.localized(language: AppLanguage): String =
    appStrings(language).menuStatusLabels[this] ?: name
